akaforum_accueil:
    path: /{page}
    defaults: { _controller: AkaForumBundle:Forum:index, page: 1 }
    requirements:
        page: "\d*"

akaforum_voir:
    path: /article/{id}
    defaults: { _controller: AkaForumBundle:Forum:voir }
    requirements:
        id:   "\d+"

akaforum_ajouter:
    path: /ajouter
    defaults: { _controller: AkaForumBundle:Forum:ajouter }

akaforum_modifier:
    path: /modifier/{id}
    defaults: { _controller: AkaForumBundle:Forum:modifier }
    requirements:
        id:   "\d+"

akaforum_supprimer:
    path: /supprimer/{id}
    defaults: { _controller: AkaForumBundle:Forum:supprimer }
    requirements:
        id:   "\d+"	

