parameters:
#    aka_forum.example.class: Aka\ForumBundle\Example

services:
#    aka_forum.example:
#        class: %aka_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
